name: Checks  # The name of the workflow

on:
  push:  # This workflow is triggered on any push event.

jobs:
  test-lint:
    name: Test and Lint  # The name of this job
    runs-on: ubuntu-20.04  # The operating system on which the job will run

    steps:
      - name: Login to Docker Hub  # Step to log in to Docker Hub
        uses: docker/login-action@v1  # Using a pre-built GitHub action to log in to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}  # Docker Hub username is obtained from GitHub secrets.
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub password is obtained from GitHub secrets.

      - name: Checkout  # Step to update the code repository
        uses: actions/checkout@v2  # Using a pre-built GitHub action to update the GitHub repository.

      - name: Test  # Test step
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"  # Using Docker to run tests in your Django application.

      - name: Lint  # Linting step
        run: docker-compose run --rm app sh -c "flake8"  # Using Docker to check the code style using Flake8.
